version: '3.8'

services:
  app:
    image: ghcr.io/maryiadevopsroom/secure-cicd:dev
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - .:/app

  mongo:
    image: mongo:8.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
